# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.CharField(default='FC', max_length=24),
            preserve_default=False,
        ),
    ]
