# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='basic_salary',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='기본급'),
        ),
    ]
