# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_basic_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pilates_GX',
            field=models.CharField(blank=True, help_text='필라테스 gx정책', max_length=32, null=True, verbose_name='필라테스 GX정책'),
        ),
        migrations.AddField(
            model_name='user',
            name='pilates_PT',
            field=models.CharField(blank=True, help_text='필라테스 PT정책', max_length=32, null=True, verbose_name='필라테스 PT정책'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(max_length=12, null=True, verbose_name='성별'),
        ),
    ]
