# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 07:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20170714_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fitness_Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('team_sales', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=19, verbose_name='팀 매출')),
                ('personal_sales', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=19, verbose_name='개인 매출')),
                ('basic_salary', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='기본급')),
                ('commission_rate', models.FloatField(default=0.0, verbose_name='커미션 비율')),
                ('commission', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='커미션')),
                ('tuition_rate', models.FloatField(default=0.0, verbose_name='수업료 비율')),
                ('tuition', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='수업료')),
                ('total', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12, verbose_name='합계')),
                ('refund', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='환불 합계')),
                ('salary', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='월급')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Salary', to=settings.AUTH_USER_MODEL, verbose_name='이름')),
            ],
        ),
    ]
