# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_fitness_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitness_salary',
            name='refund',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='환불 합계'),
        ),
        migrations.AlterField(
            model_name='fitness_salary',
            name='tuition_rate',
            field=models.IntegerField(default=0, verbose_name='수업료 비율'),
        ),
    ]
