# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20170716_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitness_salary',
            name='uid',
            field=models.IntegerField(null=True),
        ),
    ]
