# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20170716_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='fc_salary',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='팀 인원'),
        ),
        migrations.AlterField(
            model_name='fc_salary',
            name='commission_rate',
            field=models.FloatField(blank=True, default=0.0, verbose_name='커미션 비율'),
        ),
        migrations.AlterField(
            model_name='fc_salary',
            name='personal_commission_rate',
            field=models.FloatField(blank=True, default=0.0, verbose_name='개인 커미션 비율'),
        ),
    ]
