# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20170721_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fc_salary',
            name='total',
        ),
    ]
