# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_remove_fc_salary_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitness_salary',
            name='refund',
        ),
        migrations.RemoveField(
            model_name='fitness_salary',
            name='total',
        ),
        migrations.AddField(
            model_name='fitness_salary',
            name='Fitness_refund',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=19, verbose_name='Fitness팀 총 환불'),
        ),
        migrations.AddField(
            model_name='fitness_salary',
            name='personal_refund',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=19, verbose_name='개인 환불'),
        ),
    ]
