# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20170721_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilates_salary',
            name='Pilates_refund',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=19, verbose_name='Pilates팀 총 환불'),
        ),
        migrations.AddField(
            model_name='pilates_salary',
            name='personal_refund',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=19, verbose_name='개인 환불'),
        ),
    ]
