# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitness_teamledaer_commission',
            name='sales',
        ),
        migrations.AddField(
            model_name='fitness_teamledaer_commission',
            name='max_sales',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=19, verbose_name='Fitness팀 매출범위 종료'),
        ),
        migrations.AddField(
            model_name='fitness_teamledaer_commission',
            name='min_sales',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=19, verbose_name='Fitness팀 매출범위 시작'),
        ),
        migrations.AlterField(
            model_name='fc_teamleader_commission',
            name='sales',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=19, verbose_name='FC 팀매출'),
        ),
    ]
