# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20170711_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitness_teamledaer_commission',
            name='max_sales',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=19, null=True, verbose_name='Fitness팀 매출범위 종료'),
        ),
    ]
