# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20170711_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fc_personal_commission',
            name='personal_sales',
        ),
        migrations.RemoveField(
            model_name='fc_team_commission',
            name='sales',
        ),
        migrations.RemoveField(
            model_name='fc_teamleader_commission',
            name='sales',
        ),
        migrations.RemoveField(
            model_name='fitness_personal_commission',
            name='personal_sales',
        ),
        migrations.RemoveField(
            model_name='pilates_teamleader_commission',
            name='sales',
        ),
        migrations.AddField(
            model_name='fc_personal_commission',
            name='max_personal_sales',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=19, null=True, verbose_name='FC 개인 매출범위 종료'),
        ),
        migrations.AddField(
            model_name='fc_personal_commission',
            name='min_personal_sales',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=19, verbose_name='FC 개인매출범위 시작'),
        ),
        migrations.AddField(
            model_name='fc_team_commission',
            name='max_sales',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=19, null=True, verbose_name='FC 팀매출 범위 종료'),
        ),
        migrations.AddField(
            model_name='fc_team_commission',
            name='min_sales',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=19, verbose_name='FC 팀매출 범위 시작'),
        ),
        migrations.AddField(
            model_name='fc_teamleader_commission',
            name='max_sales',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=19, null=True, verbose_name='FC팀매출 범위 종료'),
        ),
        migrations.AddField(
            model_name='fc_teamleader_commission',
            name='min_sales',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=19, verbose_name='FC 팀매출 범위 시작'),
        ),
        migrations.AddField(
            model_name='fitness_personal_commission',
            name='max_personal_sales',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=19, null=True, verbose_name='Fitness 팀매출 범위 종료'),
        ),
        migrations.AddField(
            model_name='fitness_personal_commission',
            name='min_personal_sales',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=19, verbose_name='Fitness 개인매출 범위 시작'),
        ),
        migrations.AddField(
            model_name='pilates_teamleader_commission',
            name='max_sales',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=19, null=True, verbose_name='Fitness 팀매출 범위 종료'),
        ),
        migrations.AddField(
            model_name='pilates_teamleader_commission',
            name='min_sales',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=19, verbose_name='Pilates 팀매출 범위 시작'),
        ),
        migrations.AlterField(
            model_name='fitness_teamledaer_commission',
            name='max_sales',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=19, null=True, verbose_name='Fitness 팀매출 범위 종료'),
        ),
        migrations.AlterField(
            model_name='fitness_teamledaer_commission',
            name='min_sales',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=19, verbose_name='Fitness 팀매출 범위 시작'),
        ),
    ]
