# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20170711_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fc_personal_commission',
            old_name='personeel',
            new_name='personnel',
        ),
        migrations.RemoveField(
            model_name='fc_teamleader_commission',
            name='personeel',
        ),
        migrations.RemoveField(
            model_name='pilates_commission',
            name='personal_sales',
        ),
        migrations.AddField(
            model_name='pilates_commission',
            name='max_personal_sales',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=19, verbose_name='Pilates 개인매출 범위 종료'),
        ),
        migrations.AddField(
            model_name='pilates_commission',
            name='min_personal_sales',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=19, verbose_name='Pilates 개인매출 범위 시작'),
        ),
    ]
