# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20170712_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fc_personal_commission',
            options={'ordering': ['min_personal_sales']},
        ),
        migrations.AlterModelOptions(
            name='fc_team_commission',
            options={'ordering': ['min_sales']},
        ),
        migrations.AlterModelOptions(
            name='fc_teamleader_commission',
            options={'ordering': ['min_sales']},
        ),
        migrations.AlterModelOptions(
            name='fitness_personal_commission',
            options={'ordering': ['min_personal_sales']},
        ),
        migrations.AlterModelOptions(
            name='fitness_teamledaer_commission',
            options={'ordering': ['min_sales']},
        ),
        migrations.AlterModelOptions(
            name='pilates_commission',
            options={'ordering': ['min_personal_sales']},
        ),
        migrations.AlterModelOptions(
            name='pilates_teamleader_commission',
            options={'ordering': ['min_sales']},
        ),
        migrations.RemoveField(
            model_name='pilates_teamleader_commission',
            name='tuition',
        ),
        migrations.AddField(
            model_name='pilates_teamleader_commission',
            name='GX_tuition',
            field=models.DecimalField(blank=True, decimal_places=0, default=30000, max_digits=10, null=True, verbose_name='GX 수업당 수업비'),
        ),
        migrations.AddField(
            model_name='pilates_teamleader_commission',
            name='PT_tuition',
            field=models.DecimalField(blank=True, decimal_places=0, default=30000, max_digits=10, null=True, verbose_name='PT 수업당 수업비'),
        ),
    ]
