# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20170714_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pilates_GX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuition', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Pilates GX 수업당 수업비')),
                ('depending_number', models.IntegerField(default=0, verbose_name='Pilates GX 명수')),
            ],
        ),
        migrations.CreateModel(
            name='Pilates_PT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fix_rate', models.FloatField(default=0.0, verbose_name='Pilates 고정된 비율의 PT 커미션')),
            ],
        ),
        migrations.RemoveField(
            model_name='pilates_commission',
            name='tuition',
        ),
    ]
