# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20170714_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pilates_gx',
            name='depending_number',
        ),
        migrations.AddField(
            model_name='pilates_gx',
            name='depending_number_max',
            field=models.IntegerField(default=0, verbose_name='Pilates GX 최대 인원수'),
        ),
        migrations.AddField(
            model_name='pilates_gx',
            name='depending_number_min',
            field=models.IntegerField(default=0, verbose_name='Pilates GX 최소 인원수'),
        ),
    ]
