# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 09:05
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth', models.DateField(blank=True, help_text='Ex) 1980-06-30', null=True, verbose_name='생년월일')),
                ('registered_session', models.CharField(blank=True, max_length=24, verbose_name='등록세션')),
                ('PT_payment_amount', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='PT결제금액')),
                ('PT_payment_method', models.CharField(blank=True, max_length=12, verbose_name='PT결제방식')),
                ('unitprice', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='1회세션단가')),
                ('period_PT', models.CharField(blank=True, max_length=12, null=True, verbose_name='강습기간')),
                ('registered_date', models.DateField(default=django.utils.timezone.now, verbose_name='PT등록일')),
                ('Num', models.IntegerField(default=0)),
                ('Trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Trainer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='성명')),
                ('birth', models.DateField(help_text='Ex) 1980-06-30', null=True, verbose_name='생년월일')),
                ('phone_num', models.CharField(help_text='Ex) 010-1234-1234', max_length=32, null=True, validators=[django.core.validators.RegexValidator(message='휴대폰 양식으로 써주세요.', regex='^\\d{2,3}-\\d{3,4}-\\d{4}$')], verbose_name='휴대번호')),
                ('address', models.CharField(blank=True, max_length=64, null=True, verbose_name='주소')),
                ('sex', models.CharField(max_length=12, null=True, verbose_name='성별')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='등록일')),
                ('end_date', models.DateField(default=datetime.datetime(2017, 8, 8, 18, 5, 25, 544520), verbose_name='회원권종료일')),
                ('type_choice', models.CharField(default='피트니스', max_length=12, verbose_name='종류선택')),
                ('rating', models.CharField(default='Bronze', max_length=12, verbose_name='등급')),
                ('period_fitness', models.CharField(blank=True, help_text='피트니스를 선택하신분만 선택해주세요.', max_length=12, null=True, verbose_name='피트니스기간')),
                ('period_pilates', models.CharField(blank=True, help_text='필라테스를 선택하신분만 선택해주세요.', max_length=12, null=True, verbose_name='필라테스기간')),
                ('period_both', models.CharField(blank=True, max_length=12, null=True, verbose_name='피트니스+필라테스기간')),
                ('locker', models.CharField(blank=True, help_text='락카를 쓰실 분만 선택해주세요. 헬스락카는 H, 골프락카는 G', max_length=12, null=True, verbose_name='추가사항')),
                ('period_locker', models.IntegerField(blank=True, help_text='락카를 쓰실 분만 입력해주세요. 락카를 사용할 개월수를 적어주세요.', null=True, verbose_name='락카개월수')),
                ('cautions', models.CharField(blank=True, max_length=128, verbose_name='병력및주의사항')),
                ('exercise_time', models.CharField(blank=True, max_length=12, verbose_name='운동시간대')),
                ('visit_path', models.CharField(blank=True, max_length=12, verbose_name='방문경로')),
                ('payment_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='결제금액')),
                ('payment_method', models.CharField(default='카드', max_length=12, verbose_name='결제방식')),
                ('registered_session', models.CharField(blank=True, max_length=24, null=True, verbose_name='등록세션')),
                ('PT_payment_amount', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='PT결제금액')),
                ('PT_payment_method', models.CharField(blank=True, max_length=12, null=True, verbose_name='PT결제방식')),
                ('unitprice', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='1회세션단가')),
                ('period_PT', models.CharField(blank=True, max_length=12, null=True, verbose_name='강습기간')),
                ('registered_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='PT등록일')),
                ('used_session', models.IntegerField(blank=True, default=0, null=True, verbose_name='사용한 세션')),
                ('re_registered', models.BooleanField(default=False, verbose_name='재등록 여부')),
                ('Trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PT_members', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=12)),
                ('birth', models.DateField(blank=True, help_text='Ex) 1980-06-30', null=True, verbose_name='생년월일')),
                ('registered_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='해당PT등록일')),
                ('registered_session', models.CharField(blank=True, max_length=24, null=True, verbose_name='등록세션')),
                ('used_session', models.IntegerField(blank=True, default=0, null=True, verbose_name='사용한 세션')),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('Trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule', to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Member', verbose_name='회원이름')),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(max_length=12, on_delete=django.db.models.deletion.CASCADE, related_name='History', to='staff.Member', verbose_name='성명'),
        ),
    ]
