# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=24)),
                ('member_birth', models.DateField()),
                ('member_phone', models.IntegerField()),
                ('member_address', models.CharField(max_length=64)),
                ('member_sex', models.CharField(choices=[('M', '남자'), ('F', '여자')], max_length=12)),
            ],
        ),
        migrations.RenameModel(
            old_name='Profile',
            new_name='Staff',
        ),
        migrations.AddField(
            model_name='member',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Staff'),
        ),
    ]
