# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20170625_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
