# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 09:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_member_member_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_phone',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(message='휴대폰 양식으로 써주세요.', regex='^\\d{2,3}-\\d{3,4}-\\d{4}$/')]),
        ),
    ]
