# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 13:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20170709_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 8, 22, 48, 51, 470357), verbose_name='회원권종료일'),
        ),
    ]
