# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 09:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20170625_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member_address',
            new_name='주소',
        ),
        migrations.AlterField(
            model_name='member',
            name='member_phone',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(message='휴대폰 양식으로 써주세요.', regex='^\\d{2,3}-\\d{3,4}-\\d{4}$')]),
        ),
    ]
