# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 05:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20170709_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 10, 14, 1, 36, 67529), verbose_name='회원권종료일'),
        ),
    ]
