# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20170625_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member_date',
            new_name='등록일',
        ),
    ]
