# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 05:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20170711_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='number',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='GX명수'),
        ),
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 11, 14, 42, 24, 638749), verbose_name='회원권종료일'),
        ),
    ]
