# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 13:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20170625_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member_sex',
            new_name='성별',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='member_name',
            new_name='회원이름',
        ),
        migrations.RemoveField(
            model_name='member',
            name='member_birth',
        ),
        migrations.RemoveField(
            model_name='member',
            name='member_phone',
        ),
        migrations.AddField(
            model_name='member',
            name='생일',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='휴대번호',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator(message='휴대폰 양식으로 써주세요.', regex='^\\d{2,3}-\\d{3,4}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='member',
            name='주소',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
