# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 13:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20170625_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='생일',
            new_name='생년월일',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='회원이름',
            new_name='성명',
        ),
        migrations.AlterField(
            model_name='member',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='등록일',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
