# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 07:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_auto_20170712_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(null=True)),
                ('date', models.DateField(verbose_name='결제일')),
                ('end_date', models.DateField(default=datetime.datetime(2017, 8, 15, 16, 21, 44, 701666), verbose_name='회원권종료일')),
                ('payment_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='결제금액')),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='RefundHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_date', models.DateField(verbose_name='환불일')),
                ('refund_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='환불금액')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staff.PaymentHistory')),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 15, 16, 21, 44, 699665), verbose_name='회원권종료일'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PaymentHistory', to='staff.Member', verbose_name='회원'),
        ),
    ]
