# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 00:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_auto_20170625_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='생년월일',
            field=models.DateField(help_text='Ex) 1980-06-30', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='주소',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='휴대번호',
            field=models.CharField(help_text='Ex) 010-1234-1234', max_length=32, null=True, validators=[django.core.validators.RegexValidator(message='휴대폰 양식으로 써주세요.', regex='^\\d{2,3}-\\d{3,4}-\\d{4}$')]),
        ),
    ]
