# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 01:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_auto_20170716_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 16, 10, 51, 0, 479861), verbose_name='회원권종료일'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 16, 10, 51, 0, 481863), verbose_name='회원권종료일'),
        ),
    ]
