# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_auto_20170626_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='등록일',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
