# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 07:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_auto_20170717_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='registered_date',
            new_name='PT_registered_date',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='registered_date',
            new_name='PT_registered_date',
        ),
        migrations.AddField(
            model_name='member',
            name='PT_PT_registered_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='PT등록일'),
        ),
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 16, 16, 28, 12, 253457), verbose_name='회원권종료일'),
        ),
        migrations.AlterField(
            model_name='member',
            name='registered_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='등록일'),
        ),
        migrations.AlterField(
            model_name='member',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='시작일'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 16, 16, 28, 12, 255458), verbose_name='회원권종료일'),
        ),
    ]
