# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_auto_20170626_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='결제금액',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='member',
            name='결제방식',
            field=models.CharField(choices=[('현금', '현금'), ('카드', '카드')], default='카드', max_length=12),
        ),
        migrations.AddField(
            model_name='member',
            name='등급',
            field=models.CharField(choices=[('B', 'Bronze'), ('S', 'Silver'), ('G', 'Gold'), ('VIP', 'VIP')], default='Bronze', max_length=12),
        ),
        migrations.AddField(
            model_name='member',
            name='병력및주의사항',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='선택',
            field=models.CharField(choices=[('Fitness', '피트니스'), ('Pilates', '필라테스'), ('Both', '피트니스+필라테스')], default='피트니스', max_length=12),
        ),
        migrations.AddField(
            model_name='member',
            name='운동시간대',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='member',
            name='피트니스기간',
            field=models.CharField(blank=True, choices=[('1개월', '1개월'), ('3개월', '3개월'), ('6개월', '6개월'), ('12개월', '12개월')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='필라테스기간',
            field=models.CharField(blank=True, choices=[('주 2회 4주', '주 2회 4주'), ('주 3회 4주', '주 3회 4주'), ('주 2회 12주', '주 2회 12주'), ('주 3회 12주', '주 3회 12주'), ('주 2회 24주', '주 2회 24주'), ('주 3회 24주', '주 3회 24주')], max_length=12, null=True),
        ),
    ]
