# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_auto_20170626_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='락카개월수',
            field=models.IntegerField(blank=True, help_text='락카를 쓰실 분만 입력해주세요. 락카를 사용할 개월수를 적어주세요.', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='추가사항',
            field=models.CharField(blank=True, choices=[('H', 'H'), ('G', 'G')], help_text='락카를 쓰실 분만 선택해주세요.헬스락카는 H, 골프락카는 G', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='병력및주의사항',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
