# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_auto_20170626_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='추가사항',
            field=models.CharField(blank=True, choices=[('H', 'H'), ('G', 'G')], help_text='락카를 쓰실 분만 선택해주세요. 헬스락카는 H, 골프락카는 G', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='피트니스기간',
            field=models.CharField(blank=True, choices=[('1개월', '1개월'), ('3개월', '3개월'), ('6개월', '6개월'), ('12개월', '12개월')], help_text='피트니스를 선택하신분만 선택해주세요.', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='필라테스기간',
            field=models.CharField(blank=True, choices=[('주 2회 4주', '주 2회 4주'), ('주 3회 4주', '주 3회 4주'), ('주 2회 12주', '주 2회 12주'), ('주 3회 12주', '주 3회 12주'), ('주 2회 24주', '주 2회 24주'), ('주 3회 24주', '주 3회 24주')], help_text='필라테스를 선택하신분만 선택해주세요.', max_length=12, null=True),
        ),
    ]
