# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_auto_20170626_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='선택',
            new_name='종류선택',
        ),
    ]
