# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_auto_20170626_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='결제금액',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='결제방식',
            field=models.CharField(default='카드', max_length=12),
        ),
        migrations.AlterField(
            model_name='member',
            name='등급',
            field=models.CharField(default='Bronze', max_length=12),
        ),
        migrations.AlterField(
            model_name='member',
            name='성별',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='member',
            name='종류선택',
            field=models.CharField(default='피트니스', max_length=12),
        ),
        migrations.AlterField(
            model_name='member',
            name='추가사항',
            field=models.CharField(blank=True, help_text='락카를 쓰실 분만 선택해주세요. 헬스락카는 H, 골프락카는 G', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='피트니스기간',
            field=models.CharField(blank=True, help_text='피트니스를 선택하신분만 선택해주세요.', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='필라테스기간',
            field=models.CharField(blank=True, help_text='필라테스를 선택하신분만 선택해주세요.', max_length=12, null=True),
        ),
    ]
