# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 02:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0016_auto_20170627_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
