# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0017_auto_20170627_1112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
