# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 03:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0017_auto_20170718_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='registered_session',
            field=models.IntegerField(blank=True, null=True, verbose_name='등록세션'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='시작일'),
        ),
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 18, 12, 43, 34, 154559), verbose_name='회원권종료일'),
        ),
        migrations.AlterField(
            model_name='member',
            name='registered_session',
            field=models.IntegerField(blank=True, null=True, verbose_name='등록세션'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 18, 12, 43, 34, 156560), verbose_name='회원권종료일'),
        ),
    ]
