# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 11:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0018_delete_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='PT결제금액',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='PT결제방식',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='member',
            name='Trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PT_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='등록세션',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
