# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 04:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0019_auto_20170719_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundhistory',
            name='division',
            field=models.CharField(max_length=12, null=True, verbose_name='회원권/PT 구분'),
        ),
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 18, 13, 4, 11, 311595), verbose_name='회원권종료일'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 18, 13, 4, 11, 314596), verbose_name='회원권종료일'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='start_date',
            field=models.DateField(blank=True, verbose_name='시작일'),
        ),
    ]
