# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 10:39
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_member_등록횟수'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='PT결제금액',
        ),
        migrations.RemoveField(
            model_name='member',
            name='PT결제방식',
        ),
        migrations.RemoveField(
            model_name='member',
            name='결제금액',
        ),
        migrations.RemoveField(
            model_name='member',
            name='결제방식',
        ),
        migrations.RemoveField(
            model_name='member',
            name='등급',
        ),
        migrations.RemoveField(
            model_name='member',
            name='등록세션',
        ),
        migrations.RemoveField(
            model_name='member',
            name='등록일',
        ),
        migrations.RemoveField(
            model_name='member',
            name='등록횟수',
        ),
        migrations.RemoveField(
            model_name='member',
            name='락카개월수',
        ),
        migrations.RemoveField(
            model_name='member',
            name='병력및주의사항',
        ),
        migrations.RemoveField(
            model_name='member',
            name='생년월일',
        ),
        migrations.RemoveField(
            model_name='member',
            name='성명',
        ),
        migrations.RemoveField(
            model_name='member',
            name='성별',
        ),
        migrations.RemoveField(
            model_name='member',
            name='운동시간대',
        ),
        migrations.RemoveField(
            model_name='member',
            name='종류선택',
        ),
        migrations.RemoveField(
            model_name='member',
            name='주소',
        ),
        migrations.RemoveField(
            model_name='member',
            name='추가사항',
        ),
        migrations.RemoveField(
            model_name='member',
            name='피트니스기간',
        ),
        migrations.RemoveField(
            model_name='member',
            name='필라테스기간',
        ),
        migrations.RemoveField(
            model_name='member',
            name='휴대번호',
        ),
        migrations.AddField(
            model_name='member',
            name='PT_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='PT결제금액'),
        ),
        migrations.AddField(
            model_name='member',
            name='PT_payment_method',
            field=models.CharField(blank=True, max_length=12, verbose_name='PT결제방식'),
        ),
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='주소'),
        ),
        migrations.AddField(
            model_name='member',
            name='birth',
            field=models.DateField(help_text='Ex) 1980-06-30', null=True, verbose_name='생년월일'),
        ),
        migrations.AddField(
            model_name='member',
            name='cautions',
            field=models.CharField(blank=True, max_length=128, verbose_name='병력및주의사항'),
        ),
        migrations.AddField(
            model_name='member',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 1, 19, 39, 32, 439051), verbose_name='회원권종료일'),
        ),
        migrations.AddField(
            model_name='member',
            name='exercise_time',
            field=models.CharField(blank=True, max_length=12, verbose_name='운동시간대'),
        ),
        migrations.AddField(
            model_name='member',
            name='locker',
            field=models.CharField(blank=True, help_text='락카를 쓰실 분만 선택해주세요. 헬스락카는 H, 골프락카는 G', max_length=12, null=True, verbose_name='추가사항'),
        ),
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(default='익명', max_length=24, verbose_name='성명'),
        ),
        migrations.AddField(
            model_name='member',
            name='payment_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='결제금액'),
        ),
        migrations.AddField(
            model_name='member',
            name='payment_method',
            field=models.CharField(default='카드', max_length=12, verbose_name='결제방식'),
        ),
        migrations.AddField(
            model_name='member',
            name='period_PT',
            field=models.DurationField(blank=True, null=True, verbose_name='강습기간'),
        ),
        migrations.AddField(
            model_name='member',
            name='period_both',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='피트니스+필라테스기간'),
        ),
        migrations.AddField(
            model_name='member',
            name='period_fitness',
            field=models.CharField(blank=True, help_text='피트니스를 선택하신분만 선택해주세요.', max_length=12, null=True, verbose_name='피트니스기간'),
        ),
        migrations.AddField(
            model_name='member',
            name='period_locker',
            field=models.IntegerField(blank=True, help_text='락카를 쓰실 분만 입력해주세요. 락카를 사용할 개월수를 적어주세요.', null=True, verbose_name='락카개월수'),
        ),
        migrations.AddField(
            model_name='member',
            name='period_pilates',
            field=models.CharField(blank=True, help_text='필라테스를 선택하신분만 선택해주세요.', max_length=12, null=True, verbose_name='필라테스기간'),
        ),
        migrations.AddField(
            model_name='member',
            name='phone_num',
            field=models.CharField(help_text='Ex) 010-1234-1234', max_length=32, null=True, validators=[django.core.validators.RegexValidator(message='휴대폰 양식으로 써주세요.', regex='^\\d{2,3}-\\d{3,4}-\\d{4}$')], verbose_name='휴대번호'),
        ),
        migrations.AddField(
            model_name='member',
            name='rating',
            field=models.CharField(default='Bronze', max_length=12, verbose_name='등급'),
        ),
        migrations.AddField(
            model_name='member',
            name='registered_session',
            field=models.CharField(blank=True, max_length=24, verbose_name='등록세션'),
        ),
        migrations.AddField(
            model_name='member',
            name='sex',
            field=models.CharField(max_length=12, null=True, verbose_name='성별'),
        ),
        migrations.AddField(
            model_name='member',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='등록일'),
        ),
        migrations.AddField(
            model_name='member',
            name='type_choice',
            field=models.CharField(default='피트니스', max_length=12, verbose_name='종류선택'),
        ),
        migrations.AddField(
            model_name='member',
            name='unitprice',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='1회세션단가'),
        ),
        migrations.AddField(
            model_name='member',
            name='visit_path',
            field=models.CharField(blank=True, max_length=12, verbose_name='방문경로'),
        ),
    ]
