# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 10:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0022_auto_20170702_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 1, 19, 55, 30, 149891), verbose_name='회원권종료일'),
        ),
        migrations.AlterField(
            model_name='member',
            name='period_PT',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='강습기간'),
        ),
    ]
