# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 11:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0024_auto_20170702_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='period_Fitness',
            new_name='period_fitness',
        ),
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 1, 20, 40, 4, 582553), verbose_name='회원권종료일'),
        ),
    ]
