# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 04:38
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0025_auto_20170702_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_session', models.CharField(blank=True, max_length=24, verbose_name='등록세션')),
                ('PT_payment_amount', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='PT결제금액')),
                ('PT_payment_method', models.CharField(blank=True, max_length=12, verbose_name='PT결제방식')),
                ('unitprice', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='1회세션단가')),
                ('Trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Trainer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 3, 13, 38, 6, 482370), verbose_name='회원권종료일'),
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='staff.Member'),
        ),
    ]
