# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 06:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0025_auto_20170724_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='OT_used_session',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='OT 횟수'),
        ),
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 23, 15, 51, 18, 322887), verbose_name='회원권종료일'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 23, 15, 51, 18, 328417), verbose_name='회원권종료일'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='unitprice',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='1회세션단가'),
        ),
    ]
