# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 04:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0026_auto_20170704_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='unitprice',
        ),
        migrations.AddField(
            model_name='history',
            name='registered_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='PT등록일'),
        ),
        migrations.AddField(
            model_name='member',
            name='registered_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='PT등록일'),
        ),
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 3, 13, 42, 48, 238252), verbose_name='회원권종료일'),
        ),
    ]
