# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 04:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0027_auto_20170704_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='staff.Member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 3, 13, 45, 15, 8857), verbose_name='회원권종료일'),
        ),
    ]
