# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0027_auto_20170724_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='OT_used_session',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='OT 횟수'),
        ),
    ]
