# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0028_schedule_ot_used_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='locker_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='락카 금액'),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='회원권 금액'),
        ),
        migrations.AlterField(
            model_name='history',
            name='PT_registered_date',
            field=models.DateField(blank=True, verbose_name='PT등록일'),
        ),
    ]
