# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 06:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0028_auto_20170704_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='birth',
            field=models.DateField(help_text='Ex) 1980-06-30', null=True, verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 3, 15, 2, 22, 15797), verbose_name='회원권종료일'),
        ),
    ]
