# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 01:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0030_auto_20170724_2352'),
        ('staff', '0011_auto_20170717_1238'),
    ]

    operations = [
    ]
