# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 11:57
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0031_auto_20170704_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=12)),
                ('start', models.DateTimeField()),
                ('Trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Trainers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 3, 20, 57, 16, 82954), verbose_name='회원권종료일'),
        ),
    ]
