# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 12:04
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0032_auto_20170704_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 3, 21, 4, 4, 238775), verbose_name='회원권종료일'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='Trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule', to=settings.AUTH_USER_MODEL),
        ),
    ]
