# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 03:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0032_auto_20170725_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Pil_OT_used_session',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='OT 횟수'),
        ),
        migrations.AddField(
            model_name='member',
            name='Pil_Trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Pil_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='Pil_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='PT결제금액'),
        ),
        migrations.AddField(
            model_name='member',
            name='Pil_payment_method',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='PT결제방식'),
        ),
        migrations.AddField(
            model_name='member',
            name='Pil_period_PT',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='강습기간'),
        ),
        migrations.AddField(
            model_name='member',
            name='Pil_re_registered',
            field=models.BooleanField(default=False, verbose_name='Pilates재등록 여부'),
        ),
        migrations.AddField(
            model_name='member',
            name='Pil_registered_date',
            field=models.DateField(blank=True, null=True, verbose_name='Pilates_등록일'),
        ),
        migrations.AddField(
            model_name='member',
            name='Pil_registered_session',
            field=models.IntegerField(blank=True, null=True, verbose_name='등록세션'),
        ),
        migrations.AddField(
            model_name='member',
            name='Pil_status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='Pil_unitprice',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='1회세션단가'),
        ),
        migrations.AddField(
            model_name='member',
            name='Pil_used_session',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='사용한 세션'),
        ),
    ]
