# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 02:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0033_auto_20170704_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 4, 11, 50, 42, 131838), verbose_name='회원권종료일'),
        ),
    ]
