# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 06:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0034_auto_20170705_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 4, 15, 20, 5, 253179), verbose_name='회원권종료일'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
