# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 03:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0034_auto_20170726_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pil_history',
            old_name='Trainer',
            new_name='Pil_Trainer',
        ),
    ]
