# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 07:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0035_auto_20170705_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='used_session',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='사용한 세션'),
        ),
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 4, 16, 41, 0, 422959), verbose_name='회원권종료일'),
        ),
    ]
