# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 06:46
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0035_auto_20170726_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(default='new', max_length=12, verbose_name='회원구분')),
                ('birth', models.DateField(help_text='Ex) 1980-06-30', null=True, verbose_name='생년월일')),
                ('phone_num', models.CharField(help_text='Ex) 010-1234-1234', max_length=32, null=True, validators=[django.core.validators.RegexValidator(message='휴대폰 양식으로 써주세요.', regex='^\\d{2,3}-\\d{3,4}-\\d{4}$')], verbose_name='휴대번호')),
                ('address', models.CharField(blank=True, max_length=64, null=True, verbose_name='주소')),
                ('sex', models.CharField(max_length=12, null=True, verbose_name='성별')),
                ('registered_date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='등록일')),
                ('start_date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='시작일')),
                ('end_date', models.DateField(blank=True, verbose_name='회원권종료일')),
                ('type_choice', models.CharField(default='피트니스', max_length=12, verbose_name='종류선택')),
                ('rating', models.CharField(default='Bronze', max_length=12, verbose_name='등급')),
                ('period_fitness', models.CharField(blank=True, help_text='피트니스를 선택하신분만 선택해주세요.', max_length=12, null=True, verbose_name='피트니스기간')),
                ('period_pilates', models.CharField(blank=True, help_text='필라테스를 선택하신분만 선택해주세요.', max_length=12, null=True, verbose_name='필라테스기간')),
                ('period_both', models.CharField(blank=True, max_length=12, null=True, verbose_name='피트니스+필라테스기간')),
                ('locker', models.CharField(blank=True, help_text='락카를 쓰실 분만 선택해주세요. 헬스락카는 H, 골프락카는 G', max_length=12, null=True, verbose_name='추가사항')),
                ('period_locker', models.IntegerField(blank=True, help_text='락카를 쓰실 분만 입력해주세요. 락카를 사용할 개월수를 적어주세요.', null=True, verbose_name='락카개월수')),
                ('cautions', models.CharField(blank=True, max_length=128, verbose_name='병력및주의사항')),
                ('exercise_time', models.CharField(blank=True, max_length=12, verbose_name='운동시간대')),
                ('visit_path', models.CharField(blank=True, max_length=12, verbose_name='방문경로')),
                ('membership_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='회원권 금액')),
                ('locker_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='락카 금액')),
                ('payment_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='결제금액')),
                ('payment_method', models.CharField(default='카드', max_length=12, verbose_name='결제방식')),
                ('note', models.TextField(blank=True, null=True, verbose_name='비고란')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='Pil_OT_used_session',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Pilates OT 횟수'),
        ),
        migrations.AlterField(
            model_name='member',
            name='Pil_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='Pilates 결제금액'),
        ),
        migrations.AlterField(
            model_name='member',
            name='Pil_payment_method',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Pilates 결제방식'),
        ),
        migrations.AlterField(
            model_name='member',
            name='Pil_period_PT',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Pilates 강습기간'),
        ),
        migrations.AlterField(
            model_name='member',
            name='Pil_registered_date',
            field=models.DateField(blank=True, null=True, verbose_name='Pilates 등록일'),
        ),
        migrations.AlterField(
            model_name='member',
            name='Pil_registered_session',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pilates 등록세션'),
        ),
        migrations.AlterField(
            model_name='member',
            name='Pil_unitprice',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Pilates 1회세션단가'),
        ),
        migrations.AlterField(
            model_name='member',
            name='Pil_used_session',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Pilates 사용한 세션'),
        ),
        migrations.AddField(
            model_name='membershiphistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MembershipHistory', to='staff.Member', verbose_name='회원'),
        ),
    ]
