# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0036_auto_20170726_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiphistory',
            name='division',
            field=models.CharField(default='신규', max_length=12, verbose_name='회원구분'),
        ),
    ]
