# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 12:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0037_auto_20170705_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='birth',
            field=models.DateField(help_text='Ex) 1980-06-30', null=True, verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 4, 21, 48, 1, 82028), verbose_name='회원권종료일'),
        ),
    ]
