# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0037_auto_20170726_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refundhistory',
            name='refund',
        ),
        migrations.AddField(
            model_name='refundhistory',
            name='used_amount',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='사용한금액'),
        ),
    ]
