# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 03:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0039_auto_20170727_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='period_locker',
        ),
    ]
