# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 14:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0039_auto_20170705_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='registered_session',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='등록세션'),
        ),
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 4, 23, 32, 40, 817022), verbose_name='회원권종료일'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='registered_date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='해당PT등록일'),
        ),
    ]
