# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 14:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0040_auto_20170705_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='Num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 4, 23, 56, 2, 828875), verbose_name='회원권종료일'),
        ),
    ]
