# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0041_auto_20170727_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundhistory',
            name='total_utility_cost',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='총 이용금액'),
        ),
        migrations.AlterField(
            model_name='member',
            name='locker',
            field=models.CharField(blank=True, help_text='락카를 쓰실 분만 선택해주세요. 헬스락카는 H, 골프락카는 G', max_length=12, null=True, verbose_name='락카'),
        ),
        migrations.AlterField(
            model_name='refundhistory',
            name='refund_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='환급액'),
        ),
        migrations.AlterField(
            model_name='refundhistory',
            name='used_amount',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='이용료'),
        ),
    ]
