# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0042_auto_20170727_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundhistory',
            name='oneday_cost',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='1일 이용료'),
        ),
        migrations.AddField(
            model_name='refundhistory',
            name='used_period',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
