# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0043_auto_20170727_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locker_num', models.IntegerField(blank=True, null=True, verbose_name='락카 번호')),
                ('locker_type', models.CharField(blank=True, max_length=12, null=True, verbose_name='락카타입')),
                ('locker_start_date', models.DateField(blank=True, null=True, verbose_name='락카 시작일')),
                ('locker_end_date', models.DateField(blank=True, null=True, verbose_name='락카 종료일')),
                ('locker_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='락카 금액')),
                ('locker_payment_method', models.CharField(default='카드', max_length=12, verbose_name='락카결제방식')),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='locker',
        ),
        migrations.RemoveField(
            model_name='member',
            name='locker_amount',
        ),
        migrations.RemoveField(
            model_name='member',
            name='locker_end_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='locker_start_date',
        ),
        migrations.AddField(
            model_name='member',
            name='G_locker',
            field=models.IntegerField(blank=True, null=True, verbose_name='골프락카'),
        ),
        migrations.AddField(
            model_name='member',
            name='H_locker',
            field=models.IntegerField(blank=True, null=True, verbose_name='헬스락카'),
        ),
        migrations.AlterField(
            model_name='refundhistory',
            name='total_utility_cost',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='총 이용료'),
        ),
        migrations.AddField(
            model_name='locker',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locker', to='staff.Member', verbose_name='회원'),
        ),
    ]
