# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 07:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0043_auto_20170706_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Member', verbose_name='회원이름'),
        ),
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 5, 16, 16, 53, 489579), verbose_name='회원권종료일'),
        ),
    ]
