# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 05:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0044_auto_20170706_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.ForeignKey(max_length=12, on_delete=django.db.models.deletion.CASCADE, related_name='History', to='staff.Member', verbose_name='성명'),
        ),
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 7, 14, 47, 54, 397474), verbose_name='회원권종료일'),
        ),
    ]
