# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 08:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0045_auto_20170727_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
