# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 05:57
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0045_auto_20170708_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='birth',
            field=models.DateField(blank=True, help_text='Ex) 1980-06-30', null=True, verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 7, 14, 57, 39, 472091), verbose_name='회원권종료일'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='Trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='birth',
            field=models.DateField(blank=True, help_text='Ex) 1980-06-30', null=True, verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='registered_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='해당PT등록일'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='title',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
