# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 06:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0046_auto_20170708_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 7, 15, 32, 40, 640515), verbose_name='회원권종료일'),
        ),
        migrations.AlterField(
            model_name='member',
            name='sex',
            field=models.CharField(choices=[('M', '남자'), ('F', '여자')], max_length=12, null=True, verbose_name='성별'),
        ),
    ]
